require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7.8
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  CountAsOne:
    - array
    - heredoc
    - method_call
    - hash

Metrics/ClassLength:
  CountAsOne:
    - array
    - heredoc
    - method_call
    - hash

Metrics/MethodLength:
  CountAsOne:
    - array
    - heredoc
    - method_call
    - hash

Metrics/ModuleLength:
  CountAsOne:
    - array
    - heredoc
    - method_call
    - hash
