# See the writing guide of rbs: https://github.com/ruby/rbs#guides
module Merginator
  VERSION: String

  def self.pattern_merge: (*Integer, total: Integer?, wrapper: Enumerable[untyped]) -> Merginator::PatternMerge
end
