name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7.8', '3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Setup App
      run: bin/setup
    - name: Audit
      run: bundle exec bundle-audit check --update
    - name: Run tests, rubocop, and RBS
      run: bundle exec rake
